[package]
name = "wandbox"
version = "0.1.0"
authors = ["coord.e <me@coord-e.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.10.6", features = ["json"] }
