version: "3.8"
services:
  runbot:
    build: .
    depends_on:
      - redis
    environment:
      REDIS_URI: redis://redis/
      WANDBOX_HOME: https://wandbox.org/api/
      DISCORD_TOKEN: ${DISCORD_TOKEN:?}
  redis:
    image: redis:6
    command: redis-server --appendonly yes
    volumes:
      - /data
